#!/bin/bash

docker run -i -v /usr/share/ca-certificates:/usr/share/ca-certificates -v /etc/ssl:/etc/ssl -e ETCDCTL_API=3 --add-host hello.sbp.world:89.255.200.199 --rm quay.io/coreos/etcd:v3.1.0 /usr/local/bin/etcdctl --endpoints=http://172.17.0.1:4001 $@
